// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebdjhbliakyexamrjgwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZGpoYmxpYWt5ZXhhbXJqZ3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzE2MTYsImV4cCI6MjA2ODM0NzYxNn0.iMHm47V6DkIru6sNLyykzmdkmG21jqOrbeFRgC8u9eE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});